/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AdjustableSubmissionResultMap } from './adjustableSubmissionResultMap';
import type { AdjustableSubmissionAnswerMap } from './adjustableSubmissionAnswerMap';

export interface AdjustableSubmission {
  student_id: string;
  result_map?: AdjustableSubmissionResultMap;
  answer_map: AdjustableSubmissionAnswerMap;
}
