/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AdjustableQuestionResultOutput } from './adjustableQuestionResultOutput';
import type { AdjustableQuestionResultAdjustedPoints } from './adjustableQuestionResultAdjustedPoints';
import type { AdjustableQuestionResultAdjustedFeedback } from './adjustableQuestionResultAdjustedFeedback';

export interface AdjustableQuestionResult {
  /** Output generated from evaluating the answer */
  output: AdjustableQuestionResultOutput;
  /** Whether the answer passed the rule check */
  passed: boolean;
  /** Feedback or comments */
  feedback: string;
  /** ID of the rule that was applied */
  rule: string;
  /** Whether the result has been graded */
  graded?: boolean;
  /** Points awarded for this question */
  points: number;
  /** Maximum points possible */
  max_points: number;
  /** Adjusted points for this question */
  adjusted_points?: AdjustableQuestionResultAdjustedPoints;
  /** Adjusted feedback for this question */
  adjusted_feedback?: AdjustableQuestionResultAdjustedFeedback;
}
