/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssessmentCoverage } from './assessmentCoverage';

/**
 * Rubric coverage stats (None when rubric or question set is absent)
 */
export type AssessmentSummaryCoverage = AssessmentCoverage | null;
