/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssessmentCreateRequestDescription } from './assessmentCreateRequestDescription';

export interface AssessmentCreateRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** @maxLength 2000 */
  description?: AssessmentCreateRequestDescription;
}
