/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssessmentResponseDescription } from './assessmentResponseDescription';
import type { AssessmentResponseSourceUpdatedAt } from './assessmentResponseSourceUpdatedAt';
import type { AssessmentResponseQuestionSetUpdatedAt } from './assessmentResponseQuestionSetUpdatedAt';
import type { AssessmentResponseRubricUpdatedAt } from './assessmentResponseRubricUpdatedAt';
import type { AssessmentResponseResultsUpdatedAt } from './assessmentResponseResultsUpdatedAt';
import type { AssessmentResponseSummary } from './assessmentResponseSummary';

export interface AssessmentResponse {
  id: string;
  name: string;
  description?: AssessmentResponseDescription;
  created_at: string;
  updated_at: string;
  source_updated_at?: AssessmentResponseSourceUpdatedAt;
  question_set_updated_at?: AssessmentResponseQuestionSetUpdatedAt;
  rubric_updated_at?: AssessmentResponseRubricUpdatedAt;
  results_updated_at?: AssessmentResponseResultsUpdatedAt;
  /** Pre-computed summary stats */
  summary?: AssessmentResponseSummary;
}
