/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssessmentUpdateRequestName } from './assessmentUpdateRequestName';
import type { AssessmentUpdateRequestDescription } from './assessmentUpdateRequestDescription';

export interface AssessmentUpdateRequest {
  /** @maxLength 255 */
  name?: AssessmentUpdateRequestName;
  /** @maxLength 2000 */
  description?: AssessmentUpdateRequestDescription;
}
