/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssessmentSummarySubmissionCount } from './assessmentSummarySubmissionCount';
import type { AssessmentSummaryQuestionCount } from './assessmentSummaryQuestionCount';
import type { AssessmentSummaryCoverage } from './assessmentSummaryCoverage';

export interface AssessmentSummary {
  /** Raw submission count (None when no source data uploaded) */
  submission_count?: AssessmentSummarySubmissionCount;
  /** Question count (None when no question set configured) */
  question_count?: AssessmentSummaryQuestionCount;
  /** Number of graded student submissions in the database */
  graded_count?: number;
  /** Rubric coverage stats (None when rubric or question set is absent) */
  coverage?: AssessmentSummaryCoverage;
}
