/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssumptionInputName } from './assumptionInputName';
import type { AssumptionInputRule } from './assumptionInputRule';

export interface AssumptionInput {
  /** Name of the assumption */
  name?: AssumptionInputName;
  /**
   * Weight of the assumption
   * @minimum 0
   * @maximum 1
   */
  weight?: number;
  /** Rule that defines the assumption */
  rule: AssumptionInputRule;
}
