/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Mode to select which assumption to use
 */
export type AssumptionSetQuestionRuleInputMode = typeof AssumptionSetQuestionRuleInputMode[keyof typeof AssumptionSetQuestionRuleInputMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssumptionSetQuestionRuleInputMode = {
  MAX: 'MAX',
  MIN: 'MIN',
} as const;
