/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssumptionSetQuestionRuleOutputQuestionTypesItem } from './assumptionSetQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { AssumptionSetQuestionRuleOutputMode } from './assumptionSetQuestionRuleOutputMode';
import type { AssumptionOutput } from './assumptionOutput';

export interface AssumptionSetQuestionRuleOutput {
  question_types?: AssumptionSetQuestionRuleOutputQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  question_id: string;
  /** Mode to select which assumption to use */
  mode?: AssumptionSetQuestionRuleOutputMode;
  type?: 'ASSUMPTION_SET';
  /** List of assumptions in the assumption set */
  assumptions: AssumptionOutput[];
}
