/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Mode to select which assumption to use
 */
export type AssumptionSetMultiQuestionRuleInputMode = typeof AssumptionSetMultiQuestionRuleInputMode[keyof typeof AssumptionSetMultiQuestionRuleInputMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssumptionSetMultiQuestionRuleInputMode = {
  MAX: 'MAX',
  MIN: 'MIN',
} as const;
