/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssumptionSetMultiQuestionRuleOutputQuestionTypesItem } from './assumptionSetMultiQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { AssumptionSetMultiQuestionRuleOutputMode } from './assumptionSetMultiQuestionRuleOutputMode';
import type { MultiQuestionAssumptionOutput } from './multiQuestionAssumptionOutput';

export interface AssumptionSetMultiQuestionRuleOutput {
  question_types?: AssumptionSetMultiQuestionRuleOutputQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  /** Mode to select which assumption to use */
  mode?: AssumptionSetMultiQuestionRuleOutputMode;
  type?: 'ASSUMPTION_SET_MULTI';
  /** List of assumptions in the assumption set */
  assumptions: MultiQuestionAssumptionOutput[];
}
