/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssumptionSetQuestionRuleInputQuestionTypesItem } from './assumptionSetQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { AssumptionSetQuestionRuleInputMode } from './assumptionSetQuestionRuleInputMode';
import type { AssumptionInput } from './assumptionInput';

export interface AssumptionSetQuestionRuleInput {
  readonly question_types?: readonly AssumptionSetQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  /** Mode to select which assumption to use */
  mode?: AssumptionSetQuestionRuleInputMode;
  readonly type?: 'ASSUMPTION_SET';
  readonly display_name?: 'Assumption Set';
  /** List of assumptions in the assumption set */
  assumptions: AssumptionInput[];
}
