/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssumptionSetQuestionRuleOutputQuestionTypesItem } from './assumptionSetQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { AssumptionSetQuestionRuleOutputMode } from './assumptionSetQuestionRuleOutputMode';
import type { AssumptionOutput } from './assumptionOutput';

export interface AssumptionSetQuestionRuleOutput {
  readonly question_types?: readonly AssumptionSetQuestionRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  /** Mode to select which assumption to use */
  mode?: AssumptionSetQuestionRuleOutputMode;
  readonly type?: 'ASSUMPTION_SET';
  readonly display_name?: 'Assumption Set';
  /** List of assumptions in the assumption set */
  assumptions: AssumptionOutput[];
  readonly description: string;
}
