/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssumptionSetMultiQuestionRuleInputQuestionTypesItem } from './assumptionSetMultiQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { AssumptionSetMultiQuestionRuleInputMode } from './assumptionSetMultiQuestionRuleInputMode';
import type { MultiQuestionAssumptionInput } from './multiQuestionAssumptionInput';

export interface AssumptionSetMultiQuestionRuleInput {
  question_types?: AssumptionSetMultiQuestionRuleInputQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  /** Mode to select which assumption to use */
  mode?: AssumptionSetMultiQuestionRuleInputMode;
  type?: 'ASSUMPTION_SET_MULTI';
  /** List of assumptions in the assumption set */
  assumptions: MultiQuestionAssumptionInput[];
}
