/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssumptionOutputName } from './assumptionOutputName';
import type { AssumptionOutputRule } from './assumptionOutputRule';

export interface AssumptionOutput {
  /** Name of the assumption */
  name?: AssumptionOutputName;
  /**
   * Weight of the assumption
   * @minimum 0
   * @maximum 1
   */
  weight?: number;
  /** Rule that defines the assumption */
  rule: AssumptionOutputRule;
}
