/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssumptionSetMultiQuestionRuleInputQuestionTypesItem } from './assumptionSetMultiQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { AssumptionSetMultiQuestionRuleInputMode } from './assumptionSetMultiQuestionRuleInputMode';
import type { MultiQuestionAssumptionInput } from './multiQuestionAssumptionInput';

export interface AssumptionSetMultiQuestionRuleInput {
  readonly question_types?: readonly AssumptionSetMultiQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  /** Mode to select which assumption to use */
  mode?: AssumptionSetMultiQuestionRuleInputMode;
  readonly type?: 'ASSUMPTION_SET_MULTI';
  readonly display_name?: 'Assumption Set';
  /** List of assumptions in the assumption set */
  assumptions: MultiQuestionAssumptionInput[];
}
