/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { BonusRuleOutput } from './bonusRuleOutput';
import type { CompositeRuleOutput } from './compositeRuleOutput';
import type { ProgrammableRuleOutput } from './programmableRuleOutput';
import type { ProgrammingRuleOutput } from './programmingRuleOutput';
import type { TextMatchRuleOutput } from './textMatchRuleOutput';
import type { KeywordsRuleOutput } from './keywordsRuleOutput';
import type { RegexRuleOutput } from './regexRuleOutput';
import type { LengthRuleOutput } from './lengthRuleOutput';
import type { ManualRuleOutput } from './manualRuleOutput';
import type { MultiValuedRuleOutput } from './multiValuedRuleOutput';
import type { MultipleChoiceRuleOutput } from './multipleChoiceRuleOutput';
import type { NumberEqualRuleOutput } from './numberEqualRuleOutput';
import type { NumericRangeRuleOutput } from './numericRangeRuleOutput';

/**
 * Rule that defines the assumption
 */
export type AssumptionOutputRule = BonusRuleOutput | CompositeRuleOutput | ProgrammableRuleOutput | ProgrammingRuleOutput | TextMatchRuleOutput | KeywordsRuleOutput | RegexRuleOutput | LengthRuleOutput | ManualRuleOutput | MultiValuedRuleOutput | MultipleChoiceRuleOutput | NumberEqualRuleOutput | NumericRangeRuleOutput;
