/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { BodyIssueTokenAuthTokenPostGrantType } from './bodyIssueTokenAuthTokenPostGrantType';
import type { BodyIssueTokenAuthTokenPostClientId } from './bodyIssueTokenAuthTokenPostClientId';
import type { BodyIssueTokenAuthTokenPostClientSecret } from './bodyIssueTokenAuthTokenPostClientSecret';

export interface BodyIssueTokenAuthTokenPost {
  /** @pattern ^password$ */
  grant_type?: BodyIssueTokenAuthTokenPostGrantType;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyIssueTokenAuthTokenPostClientId;
  client_secret?: BodyIssueTokenAuthTokenPostClientSecret;
}
