/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { BonusRuleOutputQuestionTypesItem } from './bonusRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';

export interface BonusRuleOutput {
  readonly question_types?: readonly BonusRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'BONUS';
  readonly name?: 'Bonus';
  readonly description: string;
}
