/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { BonusQuestionRuleInputQuestionTypesItem } from './bonusQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';

export interface BonusQuestionRuleInput {
  readonly question_types?: readonly BonusQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'BONUS';
  readonly name?: 'Bonus';
}
