/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { BonusQuestionRuleOutputQuestionTypesItem } from './bonusQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';

export interface BonusQuestionRuleOutput {
  readonly question_types?: readonly BonusQuestionRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'BONUS';
  readonly display_name?: 'Bonus';
  readonly description: string;
}
