/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { BonusRuleQuestionTypesItem } from './bonusRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';

export interface BonusRule {
  question_types?: BonusRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  type?: 'BONUS';
}
