/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { GradeAdjustmentRequest } from './gradeAdjustmentRequest';

export interface BulkGradeAdjustmentRequest {
  /**
   * List of grade adjustments to apply in a single request
   * @minItems 1
   */
  adjustments: GradeAdjustmentRequest[];
}
