/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { GradingResponse } from './gradingResponse';

export interface BulkGradeAdjustmentResponse {
  /** Number of adjustments successfully applied */
  applied: number;
  /** Error messages for failed adjustments */
  errors?: string[];
  /** Updated grading results */
  result: GradingResponse;
}
