/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { CodeTestRuleInputQuestionTypesItem } from './codeTestRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { CodeTestCase } from './codeTestCase';
import type { CodeTestConfig } from './codeTestConfig';
import type { CodeTestRuleInputMode } from './codeTestRuleInputMode';

export interface CodeTestRuleInput {
  readonly id?: string;
  readonly question_types?: readonly CodeTestRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'CODE_TESTS';
  readonly display_name?: 'Code Tests';
  /**
   * List of test cases to run against the code
   * @minItems 1
   */
  testcases: CodeTestCase[];
  /** Language of the code to be tested */
  language?: 'python';
  /** Configuration for code testing */
  config?: CodeTestConfig;
  /** Whether to show the evaluated expected output in feedback */
  show_evaluated_expected?: boolean;
  /** Mode of test case evaluation: 'ALL' requires all test cases to pass, 'ANY' requires at least one to pass, 'PARTIAL' gives credit for each test case passed. */
  mode?: CodeTestRuleInputMode;
}
