/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { CompositeQuestionRuleInputQuestionTypesItem } from './compositeQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { CompositeQuestionRuleInputRulesItem } from './compositeQuestionRuleInputRulesItem';
import type { CompositeQuestionRuleInputAggregation } from './compositeQuestionRuleInputAggregation';

export interface CompositeQuestionRuleInput {
  readonly question_types?: readonly CompositeQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'COMPOSITE';
  readonly display_name?: 'Composite';
  /**
   * List of rules to apply to the answer
   * @minItems 1
   */
  rules: CompositeQuestionRuleInputRulesItem[];
  /** Aggregation method to combine rule results: 'ALL', 'ANY', or 'PARTIAL' */
  aggregation?: CompositeQuestionRuleInputAggregation;
}
