/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { BonusRule } from './bonusRule';
import type { CompositeRuleInput } from './compositeRuleInput';
import type { ProgrammableRule } from './programmableRule';
import type { ProgrammingRule } from './programmingRule';
import type { TextMatchRule } from './textMatchRule';
import type { KeywordsRule } from './keywordsRule';
import type { RegexRule } from './regexRule';
import type { LengthRule } from './lengthRule';
import type { ManualRule } from './manualRule';
import type { MultiValuedRuleInput } from './multiValuedRuleInput';
import type { MultipleChoiceRule } from './multipleChoiceRule';
import type { NumberEqualRule } from './numberEqualRule';
import type { NumericRangeRule } from './numericRangeRule';

export type CompositeRuleInputRulesItem = BonusRule | CompositeRuleInput | ProgrammableRule | ProgrammingRule | TextMatchRule | KeywordsRule | RegexRule | LengthRule | ManualRule | MultiValuedRuleInput | MultipleChoiceRule | NumberEqualRule | NumericRangeRule;
