/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { CompositeQuestionRuleOutputQuestionTypesItem } from './compositeQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { CompositeQuestionRuleOutputRulesItem } from './compositeQuestionRuleOutputRulesItem';
import type { CompositeQuestionRuleOutputAggregation } from './compositeQuestionRuleOutputAggregation';

export interface CompositeQuestionRuleOutput {
  question_types?: CompositeQuestionRuleOutputQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  question_id: string;
  type?: 'COMPOSITE';
  /**
   * List of rules to apply to the answer
   * @minItems 1
   */
  rules: CompositeQuestionRuleOutputRulesItem[];
  /** Aggregation method to combine rule results: 'ALL', 'ANY', or 'PARTIAL' */
  aggregation?: CompositeQuestionRuleOutputAggregation;
}
