/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Aggregation method to combine rule results: 'ALL', 'ANY', or 'PARTIAL'
 */
export type CompositeQuestionRuleInputAggregation = typeof CompositeQuestionRuleInputAggregation[keyof typeof CompositeQuestionRuleInputAggregation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompositeQuestionRuleInputAggregation = {
  ALL: 'ALL',
  ANY: 'ANY',
  PARTIAL: 'PARTIAL',
} as const;
