/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { CompositeRuleOutputQuestionTypesItem } from './compositeRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { CompositeRuleOutputRulesItem } from './compositeRuleOutputRulesItem';
import type { CompositeRuleOutputAggregation } from './compositeRuleOutputAggregation';

export interface CompositeRuleOutput {
  question_types?: CompositeRuleOutputQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  type?: 'COMPOSITE';
  /**
   * List of rules to apply to the answer
   * @minItems 1
   */
  rules: CompositeRuleOutputRulesItem[];
  /** Aggregation method to combine rule results: 'ALL', 'ANY', or 'PARTIAL' */
  aggregation?: CompositeRuleOutputAggregation;
}
