/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Aggregation method to combine rule results: 'ALL', 'ANY', or 'PARTIAL'
 */
export type CompositeRuleOutputAggregation = typeof CompositeRuleOutputAggregation[keyof typeof CompositeRuleOutputAggregation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompositeRuleOutputAggregation = {
  ALL: 'ALL',
  ANY: 'ANY',
  PARTIAL: 'PARTIAL',
} as const;
