/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { CompositeRuleInputQuestionTypesItem } from './compositeRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { CompositeRuleInputRulesItem } from './compositeRuleInputRulesItem';
import type { CompositeRuleInputAggregation } from './compositeRuleInputAggregation';

export interface CompositeRuleInput {
  question_types?: CompositeRuleInputQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  type?: 'COMPOSITE';
  /**
   * List of rules to apply to the answer
   * @minItems 1
   */
  rules: CompositeRuleInputRulesItem[];
  /** Aggregation method to combine rule results: 'ALL', 'ANY', or 'PARTIAL' */
  aggregation?: CompositeRuleInputAggregation;
}
