/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssumptionSetQuestionRuleInput } from './assumptionSetQuestionRuleInput';
import type { BonusQuestionRuleInput } from './bonusQuestionRuleInput';
import type { CompositeQuestionRuleInput } from './compositeQuestionRuleInput';
import type { ProgrammableQuestionRuleInput } from './programmableQuestionRuleInput';
import type { ProgrammingQuestionRuleInput } from './programmingQuestionRuleInput';
import type { SimilarityQuestionRuleInput } from './similarityQuestionRuleInput';
import type { TextMatchQuestionRuleInput } from './textMatchQuestionRuleInput';
import type { KeywordsQuestionRuleInput } from './keywordsQuestionRuleInput';
import type { RegexQuestionRuleInput } from './regexQuestionRuleInput';
import type { LengthQuestionRuleInput } from './lengthQuestionRuleInput';
import type { ManualQuestionRuleInput } from './manualQuestionRuleInput';
import type { MultiValuedQuestionRuleInput } from './multiValuedQuestionRuleInput';
import type { MultipleChoiceQuestionRuleInput } from './multipleChoiceQuestionRuleInput';
import type { NumberEqualQuestionRuleInput } from './numberEqualQuestionRuleInput';
import type { NumericRangeQuestionRuleInput } from './numericRangeQuestionRuleInput';

export type ConditionalMultiQuestionRuleInputElseRulesItem = AssumptionSetQuestionRuleInput | BonusQuestionRuleInput | CompositeQuestionRuleInput | ProgrammableQuestionRuleInput | ProgrammingQuestionRuleInput | SimilarityQuestionRuleInput | TextMatchQuestionRuleInput | KeywordsQuestionRuleInput | RegexQuestionRuleInput | LengthQuestionRuleInput | ManualQuestionRuleInput | MultiValuedQuestionRuleInput | MultipleChoiceQuestionRuleInput | NumberEqualQuestionRuleInput | NumericRangeQuestionRuleInput;
