/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ConditionalMultiQuestionRuleInputQuestionTypesItem } from './conditionalMultiQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { ConditionalMultiQuestionRuleInputIfRulesItem } from './conditionalMultiQuestionRuleInputIfRulesItem';
import type { ConditionalMultiQuestionRuleInputIfAggregation } from './conditionalMultiQuestionRuleInputIfAggregation';
import type { ConditionalMultiQuestionRuleInputThenRulesItem } from './conditionalMultiQuestionRuleInputThenRulesItem';
import type { ConditionalMultiQuestionRuleInputElseRulesItem } from './conditionalMultiQuestionRuleInputElseRulesItem';

export interface ConditionalMultiQuestionRuleInput {
  readonly question_types?: readonly ConditionalMultiQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'CONDITIONAL';
  readonly display_name?: 'Conditional';
  /**
   * List of rules to evaluate the 'if' condition
   * @minItems 1
   */
  if_rules: ConditionalMultiQuestionRuleInputIfRulesItem[];
  /** Aggregation mode for 'if' rules: 'AND' requires all to be true, 'OR' requires at least one to be true */
  if_aggregation?: ConditionalMultiQuestionRuleInputIfAggregation;
  /**
   * List of rules to evaluate if 'if' condition is met
   * @minItems 1
   */
  then_rules: ConditionalMultiQuestionRuleInputThenRulesItem[];
  /** List of rules to evaluate if 'if' condition is not met */
  else_rules: ConditionalMultiQuestionRuleInputElseRulesItem[];
}
