/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssumptionSetQuestionRuleOutput } from './assumptionSetQuestionRuleOutput';
import type { BonusQuestionRule } from './bonusQuestionRule';
import type { CompositeQuestionRuleOutput } from './compositeQuestionRuleOutput';
import type { ProgrammableQuestionRule } from './programmableQuestionRule';
import type { ProgrammingQuestionRule } from './programmingQuestionRule';
import type { TextMatchQuestionRule } from './textMatchQuestionRule';
import type { KeywordsQuestionRule } from './keywordsQuestionRule';
import type { RegexQuestionRule } from './regexQuestionRule';
import type { LengthQuestionRule } from './lengthQuestionRule';
import type { ManualQuestionRule } from './manualQuestionRule';
import type { MultiValuedQuestionRuleOutput } from './multiValuedQuestionRuleOutput';
import type { MultipleChoiceQuestionRule } from './multipleChoiceQuestionRule';
import type { NumberEqualQuestionRule } from './numberEqualQuestionRule';
import type { NumericRangeQuestionRule } from './numericRangeQuestionRule';

export type ConditionalMultiQuestionRuleOutputIfRulesItem = AssumptionSetQuestionRuleOutput | BonusQuestionRule | CompositeQuestionRuleOutput | ProgrammableQuestionRule | ProgrammingQuestionRule | TextMatchQuestionRule | KeywordsQuestionRule | RegexQuestionRule | LengthQuestionRule | ManualQuestionRule | MultiValuedQuestionRuleOutput | MultipleChoiceQuestionRule | NumberEqualQuestionRule | NumericRangeQuestionRule;
