/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Aggregation mode for 'if' rules: 'AND' requires all to be true, 'OR' requires at least one to be true
 */
export type ConditionalMultiQuestionRuleInputIfAggregation = typeof ConditionalMultiQuestionRuleInputIfAggregation[keyof typeof ConditionalMultiQuestionRuleInputIfAggregation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConditionalMultiQuestionRuleInputIfAggregation = {
  AND: 'AND',
  OR: 'OR',
} as const;
