/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ConditionalMultiQuestionRuleOutputQuestionTypesItem } from './conditionalMultiQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { ConditionalMultiQuestionRuleOutputIfRulesItem } from './conditionalMultiQuestionRuleOutputIfRulesItem';
import type { ConditionalMultiQuestionRuleOutputIfAggregation } from './conditionalMultiQuestionRuleOutputIfAggregation';
import type { ConditionalMultiQuestionRuleOutputThenRulesItem } from './conditionalMultiQuestionRuleOutputThenRulesItem';
import type { ConditionalMultiQuestionRuleOutputElseRulesItem } from './conditionalMultiQuestionRuleOutputElseRulesItem';

export interface ConditionalMultiQuestionRuleOutput {
  question_types?: ConditionalMultiQuestionRuleOutputQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  type?: 'CONDITIONAL';
  /**
   * List of rules to evaluate the 'if' condition
   * @minItems 1
   */
  if_rules: ConditionalMultiQuestionRuleOutputIfRulesItem[];
  /** Aggregation mode for 'if' rules: 'AND' requires all to be true, 'OR' requires at least one to be true */
  if_aggregation?: ConditionalMultiQuestionRuleOutputIfAggregation;
  /**
   * List of rules to evaluate if 'if' condition is met
   * @minItems 1
   */
  then_rules: ConditionalMultiQuestionRuleOutputThenRulesItem[];
  /** List of rules to evaluate if 'if' condition is not met */
  else_rules: ConditionalMultiQuestionRuleOutputElseRulesItem[];
}
