/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { CoverageRequestRubric } from './coverageRequestRubric';
import type { CoverageRequestQuestionSet } from './coverageRequestQuestionSet';

export interface CoverageRequest {
  use_stored_rubric?: boolean;
  use_stored_question_set?: boolean;
  rubric?: CoverageRequestRubric;
  question_set?: CoverageRequestQuestionSet;
}
