/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { CsvRawSubmissionsConfigAnswerColumns } from './csvRawSubmissionsConfigAnswerColumns';
import type { CsvRawSubmissionsConfigPointColumns } from './csvRawSubmissionsConfigPointColumns';

export interface CsvRawSubmissionsConfig {
  name?: 'csv';
  format?: 'csv';
  student_id_column?: string;
  answer_columns?: CsvRawSubmissionsConfigAnswerColumns;
  /** Optional mapping of question_id -> CSV column name containing pre-existing points. When provided, those questions get pre-populated result_map entries with pass-through points, bypassing rule grading for questions without a matching rule. */
  point_columns?: CsvRawSubmissionsConfigPointColumns;
}
