/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { CsvRawSubmissionsConfigPointColumnsAnyOf } from './csvRawSubmissionsConfigPointColumnsAnyOf';

/**
 * Optional mapping of question_id -> CSV column name containing pre-existing points. When provided, those questions get pre-populated result_map entries with pass-through points, bypassing rule grading for questions without a matching rule.
 */
export type CsvRawSubmissionsConfigPointColumns = CsvRawSubmissionsConfigPointColumnsAnyOf | null;
