/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

export interface CsvSubmissionsConfig {
  format?: 'csv';
  student_id_column?: string;
  include_answers?: boolean;
  include_per_question_results?: boolean;
  include_feedback?: boolean;
  include_total?: boolean;
  include_remarks?: boolean;
  include_rounded_total?: boolean;
  rounding_base?: number;
}
