/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { CustomCodeQuestionRuleInputQuestionTypesItem } from './customCodeQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { CustomCodeQuestionRuleInputParameters } from './customCodeQuestionRuleInputParameters';
import type { CustomCodeQuestionRuleInputMode } from './customCodeQuestionRuleInputMode';

export interface CustomCodeQuestionRuleInput {
  readonly id?: string;
  readonly question_types?: readonly CustomCodeQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly scope?: 'question';
  question_id: string;
  readonly type?: 'CUSTOM_CODE';
  readonly display_name?: 'Custom Code';
  /** Code to evaluate the answer. Required variables: 'output', 'passed'. Optional variable: 'feedback'. */
  code?: string;
  /** Parameters that can be used in the code. */
  parameters?: CustomCodeQuestionRuleInputParameters;
  /** Mode of evaluation: 'PASS_FAIL' uses a boolean 'passed' variable, 'OUTPUT' uses the 'output' variable (0-1) for scoring. */
  mode?: CustomCodeQuestionRuleInputMode;
}
