/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Mode of evaluation: 'PASS_FAIL' uses 'passed' per question, 'OUTPUT' uses 'output' (0-1) per question for scoring.
 */
export type CustomCodeMultiQuestionRuleInputMode = typeof CustomCodeMultiQuestionRuleInputMode[keyof typeof CustomCodeMultiQuestionRuleInputMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomCodeMultiQuestionRuleInputMode = {
  PASS_FAIL: 'PASS_FAIL',
  OUTPUT: 'OUTPUT',
} as const;
