/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { CustomCodeMultiQuestionRuleInputQuestionTypesItem } from './customCodeMultiQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { CustomCodeMultiQuestionRuleInputParameters } from './customCodeMultiQuestionRuleInputParameters';
import type { CustomCodeMultiQuestionRuleInputMode } from './customCodeMultiQuestionRuleInputMode';

export interface CustomCodeMultiQuestionRuleInput {
  readonly id?: string;
  readonly question_types?: readonly CustomCodeMultiQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly scope?: 'global';
  readonly type?: 'CUSTOM_CODE_MULTI';
  readonly display_name?: 'Custom Code';
  /**
   * List of question IDs this rule targets.
   * @minItems 1
   */
  target_question_ids: string[];
  /** Code to evaluate the answer_map. Required variable: 'results' (dict mapping question_id -> dict with 'output', 'passed', and optionally 'feedback'). */
  code?: string;
  /** Parameters that can be used in the code. */
  parameters?: CustomCodeMultiQuestionRuleInputParameters;
  /** Mode of evaluation: 'PASS_FAIL' uses 'passed' per question, 'OUTPUT' uses 'output' (0-1) per question for scoring. */
  mode?: CustomCodeMultiQuestionRuleInputMode;
}
