/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { CustomCodeRuleOutputQuestionTypesItem } from './customCodeRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { CustomCodeRuleOutputParameters } from './customCodeRuleOutputParameters';
import type { CustomCodeRuleOutputMode } from './customCodeRuleOutputMode';

export interface CustomCodeRuleOutput {
  readonly id: string;
  readonly question_types: readonly CustomCodeRuleOutputQuestionTypesItem[];
  readonly constraints: readonly QuestionConstraint[];
  readonly type: 'CUSTOM_CODE';
  readonly display_name: 'Custom Code';
  /** Code to evaluate the answer. Required variables: 'output', 'passed'. Optional variable: 'feedback'. */
  code: string;
  /** Parameters that can be used in the code. */
  parameters: CustomCodeRuleOutputParameters;
  /** Mode of evaluation: 'PASS_FAIL' uses a boolean 'passed' variable, 'OUTPUT' uses the 'output' variable (0-1) for scoring. */
  mode: CustomCodeRuleOutputMode;
  readonly description: string;
}
