/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ExactMatchQuestionRuleQuestionTypesItem } from './exactMatchQuestionRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';

export interface ExactMatchQuestionRule {
  question_types?: ExactMatchQuestionRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  question_id: string;
  /** Maximum points for the question */
  max_points?: number;
  type?: 'EXACT_MATCH';
  /**
   * List of acceptable exact answers
   * @minItems 1
   */
  answers: string[];
}
