/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ExactMatchRuleQuestionTypesItem } from './exactMatchRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';

export interface ExactMatchRule {
  question_types?: ExactMatchRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  type?: 'EXACT_MATCH';
  /**
   * List of acceptable exact answers
   * @minItems 1
   */
  answers: string[];
}
