/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ExamplifyRuleConfigChoiceMode } from './examplifyRuleConfigChoiceMode';
import type { ExamplifyRuleConfigMultiValuedMode } from './examplifyRuleConfigMultiValuedMode';

export interface ExamplifyRuleConfig {
  name?: 'examplify';
  format?: 'csv';
  include_thrown_out?: boolean;
  /** Parse numeric-like FITB blanks as NUMERIC; else treat all as TEXT. */
  parse_answer_string?: boolean;
  /** Ignore empty tokens in alternatives (e.g., trailing '|'). */
  skip_empty_alternatives?: boolean;
  choice_mode?: ExamplifyRuleConfigChoiceMode;
  multi_valued_mode?: ExamplifyRuleConfigMultiValuedMode;
}
