/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

export interface ExportQuestionSetResponse {
  filename: string;
  data: string;
  extension: string;
  media_type: string;
}
