/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AdjustableSubmission } from './adjustableSubmission';
import type { SectionStatus } from './sectionStatus';

export interface GradingResponse {
  submissions: AdjustableSubmission[];
  status: SectionStatus;
}
