/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { GradingJobFinishedAt } from './gradingJobFinishedAt';
import type { GradingJobDurationSeconds } from './gradingJobDurationSeconds';
import type { GradingJobEstimatedDurationSeconds } from './gradingJobEstimatedDurationSeconds';
import type { GradingJobEstimatedCompletionAt } from './gradingJobEstimatedCompletionAt';
import type { GradingJobStatus } from './gradingJobStatus';
import type { GradingJobError } from './gradingJobError';

export interface GradingJob {
  finished_at?: GradingJobFinishedAt;
  duration_seconds?: GradingJobDurationSeconds;
  estimated_duration_seconds?: GradingJobEstimatedDurationSeconds;
  estimated_completion_at?: GradingJobEstimatedCompletionAt;
  job_id: string;
  url: string;
  status: GradingJobStatus;
  error?: GradingJobError;
  created_at: string;
}
