/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

export type GradingJobStatus = typeof GradingJobStatus[keyof typeof GradingJobStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GradingJobStatus = {
  queued: 'queued',
  running: 'running',
  completed: 'completed',
  failed: 'failed',
} as const;
