/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { GradingJobCompletedAt } from './gradingJobCompletedAt';
import type { GradingJobDurationSeconds } from './gradingJobDurationSeconds';
import type { GradingJobEstimatedDurationSeconds } from './gradingJobEstimatedDurationSeconds';
import type { GradingJobEstimatedCompletionAt } from './gradingJobEstimatedCompletionAt';

export interface GradingJob {
  is_completed: boolean;
  completed_at?: GradingJobCompletedAt;
  duration_seconds?: GradingJobDurationSeconds;
  estimated_duration_seconds?: GradingJobEstimatedDurationSeconds;
  estimated_completion_at?: GradingJobEstimatedCompletionAt;
  job_id: string;
  url: string;
  created_at: string;
}
