/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * How to select limited submissions: 'first' (deterministic) or 'random'.
 */
export type GradingLimitConfigSelection = typeof GradingLimitConfigSelection[keyof typeof GradingLimitConfigSelection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GradingLimitConfigSelection = {
  first: 'first',
  random: 'random',
} as const;
