/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { GradedSubmissionAnswerMap } from './gradedSubmissionAnswerMap';
import type { QuestionResult } from './questionResult';

export interface GradedSubmission {
  student_id: string;
  answer_map: GradedSubmissionAnswerMap;
  results: QuestionResult[];
}
