/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { GradeAdjustmentRequestAdjustedPoints } from './gradeAdjustmentRequestAdjustedPoints';
import type { GradeAdjustmentRequestAdjustedFeedback } from './gradeAdjustmentRequestAdjustedFeedback';

export interface GradeAdjustmentRequest {
  /** Student ID to adjust */
  student_id: string;
  /** Question ID to adjust */
  question_id: string;
  /**
   * New points (optional)
   * @minimum 0
   */
  adjusted_points?: GradeAdjustmentRequestAdjustedPoints;
  /** New feedback (optional) */
  adjusted_feedback?: GradeAdjustmentRequestAdjustedFeedback;
}
