/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

export interface GradingRunRequest {
  /** When True, clear all manual adjustments on re-graded submissions. */
  remove_adjustments?: boolean;
}
