/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * If provided, preview only this many submissions.
 * @minimum 1
 * @maximum 20
 */
export type GradingLimitConfigLimit = number | null;
