/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

export type GradingJobResultType = typeof GradingJobResultType[keyof typeof GradingJobResultType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GradingJobResultType = {
  run: 'run',
  preview: 'preview',
} as const;
