/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { GradingLimitConfigLimit } from './gradingLimitConfigLimit';
import type { GradingLimitConfigSelection } from './gradingLimitConfigSelection';
import type { GradingLimitConfigSeed } from './gradingLimitConfigSeed';

export interface GradingLimitConfig {
  /**
   * If provided, preview only this many submissions.
   * @minimum 1
   * @maximum 20
   */
  limit?: GradingLimitConfigLimit;
  /** How to select limited submissions: 'first' (deterministic) or 'random'. */
  selection?: GradingLimitConfigSelection;
  /** Random seed used when selection='random' for reproducibility. */
  seed?: GradingLimitConfigSeed;
}
