/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AdjustableSubmission } from './adjustableSubmission';
import type { SectionStatus } from './sectionStatus';

export interface GradingPreviewResponse {
  submissions: AdjustableSubmission[];
  status: SectionStatus;
  answer_question_ids?: string[];
  result_question_ids?: string[];
}
