/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ExamplifyParseConfig } from './examplifyParseConfig';

export interface ImportQuestionSetRequest {
  /** Source content; str or bytes */
  data: string;
  adapter: ExamplifyParseConfig;
}
