/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { InferQuestionSetRequestRawSubmissions } from './inferQuestionSetRequestRawSubmissions';

export interface InferQuestionSetRequest {
  use_stored_submissions?: boolean;
  raw_submissions?: InferQuestionSetRequestRawSubmissions;
  choice_delimiter?: string;
  choice_option_limit?: number;
  multi_value_delimiter?: string;
  /** If true, store as question set */
  commit?: boolean;
}
