/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { KeywordsQuestionRuleInputQuestionTypesItem } from './keywordsQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { KeywordsQuestionRuleInputMode } from './keywordsQuestionRuleInputMode';

export interface KeywordsQuestionRuleInput {
  readonly question_types?: readonly KeywordsQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'KEYWORDS';
  readonly name?: 'Keywords';
  /**
   * List of keywords that must be present in the answer
   * @minItems 1
   */
  keywords: string[];
  /** Mode of keyword matching: 'ALL' requires all keywords to be present, 'ANY' requires at least one.'PARTIAL' gives credit for each keyword present. */
  mode?: KeywordsQuestionRuleInputMode;
}
