/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { KeywordsRuleOutputQuestionTypesItem } from './keywordsRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { KeywordsRuleOutputMode } from './keywordsRuleOutputMode';

export interface KeywordsRuleOutput {
  readonly question_types?: readonly KeywordsRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'KEYWORDS';
  readonly display_name?: 'Keywords';
  /**
   * List of keywords that must be present in the answer
   * @minItems 1
   */
  keywords: string[];
  /** Mode of keyword matching: 'ALL' requires all keywords to be present, 'ANY' requires at least one.'PARTIAL' gives credit for each keyword present. */
  mode?: KeywordsRuleOutputMode;
  readonly description: string;
}
