/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Mode of keyword matching: 'ALL' requires all keywords to be present, 'ANY' requires at least one.'PARTIAL' gives credit for each keyword present.
 */
export type KeywordsQuestionRuleOutputMode = typeof KeywordsQuestionRuleOutputMode[keyof typeof KeywordsQuestionRuleOutputMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KeywordsQuestionRuleOutputMode = {
  ALL: 'ALL',
  ANY: 'ANY',
  PARTIAL: 'PARTIAL',
} as const;
