/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { KeywordsRuleQuestionTypesItem } from './keywordsRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { KeywordsRuleMode } from './keywordsRuleMode';

export interface KeywordsRule {
  question_types?: KeywordsRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  type?: 'KEYWORDS';
  /**
   * List of keywords that must be present in the answer
   * @minItems 1
   */
  keywords: string[];
  /** Mode of keyword matching: 'ALL' requires all keywords to be present, 'ANY' requires at least one.'PARTIAL' gives credit for each keyword present. */
  mode?: KeywordsRuleMode;
}
