/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { LengthRuleOutputQuestionTypesItem } from './lengthRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { LengthRuleOutputMinLength } from './lengthRuleOutputMinLength';
import type { LengthRuleOutputMaxLength } from './lengthRuleOutputMaxLength';
import type { LengthRuleOutputMode } from './lengthRuleOutputMode';

export interface LengthRuleOutput {
  readonly question_types?: readonly LengthRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'LENGTH';
  readonly display_name?: 'Length';
  /** Minimum length of the answer */
  min_length?: LengthRuleOutputMinLength;
  /** Maximum length of the answer */
  max_length?: LengthRuleOutputMaxLength;
  /** Mode of length measurement */
  mode?: LengthRuleOutputMode;
  readonly description: string;
}
