/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { LengthQuestionRuleQuestionTypesItem } from './lengthQuestionRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { LengthQuestionRuleMinLength } from './lengthQuestionRuleMinLength';
import type { LengthQuestionRuleMaxLength } from './lengthQuestionRuleMaxLength';
import type { LengthQuestionRuleMode } from './lengthQuestionRuleMode';

export interface LengthQuestionRule {
  question_types?: LengthQuestionRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  question_id: string;
  type?: 'LENGTH';
  /** Minimum length of the answer */
  min_length?: LengthQuestionRuleMinLength;
  /** Maximum length of the answer */
  max_length?: LengthQuestionRuleMaxLength;
  /** Mode of length measurement */
  mode?: LengthQuestionRuleMode;
}
