/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { LengthQuestionRuleOutputQuestionTypesItem } from './lengthQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { LengthQuestionRuleOutputMinLength } from './lengthQuestionRuleOutputMinLength';
import type { LengthQuestionRuleOutputMaxLength } from './lengthQuestionRuleOutputMaxLength';
import type { LengthQuestionRuleOutputMode } from './lengthQuestionRuleOutputMode';

export interface LengthQuestionRuleOutput {
  readonly question_types?: readonly LengthQuestionRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'LENGTH';
  readonly display_name?: 'Length';
  /** Minimum length of the answer */
  min_length?: LengthQuestionRuleOutputMinLength;
  /** Maximum length of the answer */
  max_length?: LengthQuestionRuleOutputMaxLength;
  /** Mode of length measurement */
  mode?: LengthQuestionRuleOutputMode;
  readonly description: string;
}
