/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { LengthRuleInputQuestionTypesItem } from './lengthRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { LengthRuleInputMinLength } from './lengthRuleInputMinLength';
import type { LengthRuleInputMaxLength } from './lengthRuleInputMaxLength';
import type { LengthRuleInputMode } from './lengthRuleInputMode';

export interface LengthRuleInput {
  readonly question_types?: readonly LengthRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'LENGTH';
  readonly display_name?: 'Length';
  /** Minimum length of the answer */
  min_length?: LengthRuleInputMinLength;
  /** Maximum length of the answer */
  max_length?: LengthRuleInputMaxLength;
  /** Mode of length measurement */
  mode?: LengthRuleInputMode;
}
