/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Mode of length measurement
 */
export type LengthRuleMode = typeof LengthRuleMode[keyof typeof LengthRuleMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LengthRuleMode = {
  words: 'words',
  characters: 'characters',
} as const;
