/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { LengthQuestionRuleInputQuestionTypesItem } from './lengthQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { LengthQuestionRuleInputMinLength } from './lengthQuestionRuleInputMinLength';
import type { LengthQuestionRuleInputMaxLength } from './lengthQuestionRuleInputMaxLength';
import type { LengthQuestionRuleInputMode } from './lengthQuestionRuleInputMode';

export interface LengthQuestionRuleInput {
  readonly question_types?: readonly LengthQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'LENGTH';
  readonly name?: 'Length';
  /** Minimum length of the answer */
  min_length?: LengthQuestionRuleInputMinLength;
  /** Maximum length of the answer */
  max_length?: LengthQuestionRuleInputMaxLength;
  /** Mode of length measurement */
  mode?: LengthQuestionRuleInputMode;
}
