/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Mode of length measurement
 */
export type LengthRuleInputMode = typeof LengthRuleInputMode[keyof typeof LengthRuleInputMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LengthRuleInputMode = {
  words: 'words',
  characters: 'characters',
} as const;
