/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { LengthRuleQuestionTypesItem } from './lengthRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { LengthRuleMinLength } from './lengthRuleMinLength';
import type { LengthRuleMaxLength } from './lengthRuleMaxLength';
import type { LengthRuleMode } from './lengthRuleMode';

export interface LengthRule {
  question_types?: LengthRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  type?: 'LENGTH';
  /** Minimum length of the answer */
  min_length?: LengthRuleMinLength;
  /** Maximum length of the answer */
  max_length?: LengthRuleMaxLength;
  /** Mode of length measurement */
  mode?: LengthRuleMode;
}
