/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ManualQuestionRuleInputQuestionTypesItem } from './manualQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';

export interface ManualQuestionRuleInput {
  readonly question_types?: readonly ManualQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'MANUAL';
  readonly name?: 'Manual';
}
