/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ManualQuestionRuleQuestionTypesItem } from './manualQuestionRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';

export interface ManualQuestionRule {
  question_types?: ManualQuestionRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  question_id: string;
  type?: 'MANUAL';
}
