/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ManualRuleOutputQuestionTypesItem } from './manualRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';

export interface ManualRuleOutput {
  readonly question_types?: readonly ManualRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'MANUAL';
  readonly display_name?: 'Manual';
  readonly description: string;
}
