/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ManualQuestionRuleOutputQuestionTypesItem } from './manualQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';

export interface ManualQuestionRuleOutput {
  readonly question_types?: readonly ManualQuestionRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'MANUAL';
  readonly display_name?: 'Manual';
  readonly description: string;
}
