/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { MultiValuedQuestionRuleInputQuestionTypesItem } from './multiValuedQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { MultiValuedQuestionRuleInputRulesItem } from './multiValuedQuestionRuleInputRulesItem';
import type { MultiValuedQuestionRuleInputAggregation } from './multiValuedQuestionRuleInputAggregation';

export interface MultiValuedQuestionRuleInput {
  readonly question_types?: readonly MultiValuedQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'MULTI_VALUED';
  readonly name?: 'Multi Valued';
  /**
   * List of rules to apply to each value in the multi-valued answer
   * @minItems 1
   */
  rules: MultiValuedQuestionRuleInputRulesItem[];
  /** Aggregation method */
  aggregation?: MultiValuedQuestionRuleInputAggregation;
}
