/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { MultiQuestionAssumptionInputName } from './multiQuestionAssumptionInputName';
import type { MultiQuestionAssumptionInputRulesItem } from './multiQuestionAssumptionInputRulesItem';

export interface MultiQuestionAssumptionInput {
  /** Name of the assumption */
  name?: MultiQuestionAssumptionInputName;
  /**
   * Weight of the assumption
   * @minimum 0
   * @maximum 1
   */
  weight?: number;
  /** List of rules that define the assumption */
  rules: MultiQuestionAssumptionInputRulesItem[];
}
