/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Aggregation method
 */
export type MultiValuedQuestionRuleOutputAggregation = typeof MultiValuedQuestionRuleOutputAggregation[keyof typeof MultiValuedQuestionRuleOutputAggregation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MultiValuedQuestionRuleOutputAggregation = {
  ALL: 'ALL',
  ANY: 'ANY',
  PARTIAL: 'PARTIAL',
} as const;
