/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { MultipleChoiceRuleQuestionTypesItem } from './multipleChoiceRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { MultipleChoiceRuleMode } from './multipleChoiceRuleMode';

export interface MultipleChoiceRule {
  question_types?: MultipleChoiceRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  type?: 'MULTIPLE_CHOICE';
  /**
   * Set of correct choices
   * @minItems 1
   */
  answer: string[];
  /** Mode of choice matching: 'ALL' requires all correct choices to be selected, 'ANY' requires at least one, 'PARTIAL' gives credit for each correct choice selected minus each incorrect choice selected. */
  mode?: MultipleChoiceRuleMode;
}
