/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssumptionSetQuestionRuleOutput } from './assumptionSetQuestionRuleOutput';
import type { BonusQuestionRuleOutput } from './bonusQuestionRuleOutput';
import type { CompositeQuestionRuleOutput } from './compositeQuestionRuleOutput';
import type { ProgrammableQuestionRuleOutput } from './programmableQuestionRuleOutput';
import type { ProgrammingQuestionRuleOutput } from './programmingQuestionRuleOutput';
import type { TextMatchQuestionRuleOutput } from './textMatchQuestionRuleOutput';
import type { KeywordsQuestionRuleOutput } from './keywordsQuestionRuleOutput';
import type { RegexQuestionRuleOutput } from './regexQuestionRuleOutput';
import type { LengthQuestionRuleOutput } from './lengthQuestionRuleOutput';
import type { ManualQuestionRuleOutput } from './manualQuestionRuleOutput';
import type { MultiValuedQuestionRuleOutput } from './multiValuedQuestionRuleOutput';
import type { MultipleChoiceQuestionRuleOutput } from './multipleChoiceQuestionRuleOutput';
import type { NumberEqualQuestionRuleOutput } from './numberEqualQuestionRuleOutput';
import type { NumericRangeQuestionRuleOutput } from './numericRangeQuestionRuleOutput';

export type MultiQuestionAssumptionOutputRulesItem = AssumptionSetQuestionRuleOutput | BonusQuestionRuleOutput | CompositeQuestionRuleOutput | ProgrammableQuestionRuleOutput | ProgrammingQuestionRuleOutput | TextMatchQuestionRuleOutput | KeywordsQuestionRuleOutput | RegexQuestionRuleOutput | LengthQuestionRuleOutput | ManualQuestionRuleOutput | MultiValuedQuestionRuleOutput | MultipleChoiceQuestionRuleOutput | NumberEqualQuestionRuleOutput | NumericRangeQuestionRuleOutput;
