/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Mode of choice matching: 'ALL' requires all specified choices to be selected, 'CONTAIN' requires all specified choices to be selected but allows extra choices, 'NOT_CONTAIN' requires none of the specified choices to be selected, 'ANY' requires at least one of the specified choices to be selected, 'PARTIAL' gives credit for each specified choice selected minus each unspecified choice selected.
 */
export type MultipleChoiceQuestionRuleInputMode = typeof MultipleChoiceQuestionRuleInputMode[keyof typeof MultipleChoiceQuestionRuleInputMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MultipleChoiceQuestionRuleInputMode = {
  ALL: 'ALL',
  CONTAIN: 'CONTAIN',
  NOT_CONTAIN: 'NOT_CONTAIN',
  ANY: 'ANY',
  PARTIAL: 'PARTIAL',
} as const;
