/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

export type MultipleChoiceRuleQuestionTypesItem = typeof MultipleChoiceRuleQuestionTypesItem[keyof typeof MultipleChoiceRuleQuestionTypesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MultipleChoiceRuleQuestionTypesItem = {
  TEXT: 'TEXT',
  CHOICE: 'CHOICE',
  NUMERIC: 'NUMERIC',
  MULTI_VALUED: 'MULTI_VALUED',
} as const;
