/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { MultiQuestionAssumptionOutputName } from './multiQuestionAssumptionOutputName';
import type { MultiQuestionAssumptionOutputRulesItem } from './multiQuestionAssumptionOutputRulesItem';

export interface MultiQuestionAssumptionOutput {
  /** Name of the assumption */
  name?: MultiQuestionAssumptionOutputName;
  /**
   * Weight of the assumption
   * @minimum 0
   * @maximum 1
   */
  weight?: number;
  /** List of rules that define the assumption */
  rules: MultiQuestionAssumptionOutputRulesItem[];
}
