/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

export interface MultiValuedParserConfig {
  /** Marker indicating an empty answer. */
  empty_marker?: string;
  /** Whether to trim leading and trailing whitespace from raw answers. */
  trim_whitespace?: boolean;
  /** Whether to normalize the case of raw answers. */
  normalize_case?: boolean;
  /** Delimiter for separating multiple-valued raw answers. */
  delimiter?: string;
}
