/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { MultiValuedRuleOutputQuestionTypesItem } from './multiValuedRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { MultiValuedRuleOutputRulesItem } from './multiValuedRuleOutputRulesItem';
import type { MultiValuedRuleOutputAggregation } from './multiValuedRuleOutputAggregation';

export interface MultiValuedRuleOutput {
  question_types?: MultiValuedRuleOutputQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  type?: 'MULTI_VALUED';
  /**
   * List of rules to apply to each value in the multi-valued answer
   * @minItems 1
   */
  rules: MultiValuedRuleOutputRulesItem[];
  /** Aggregation method */
  aggregation?: MultiValuedRuleOutputAggregation;
}
