/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { MultiValuedQuestionRuleInputQuestionTypesItem } from './multiValuedQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { MultiValuedQuestionRuleInputRulesItem } from './multiValuedQuestionRuleInputRulesItem';
import type { MultiValuedQuestionRuleInputAggregation } from './multiValuedQuestionRuleInputAggregation';

export interface MultiValuedQuestionRuleInput {
  question_types?: MultiValuedQuestionRuleInputQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  question_id: string;
  type?: 'MULTI_VALUED';
  /**
   * List of rules to apply to each value in the multi-valued answer
   * @minItems 1
   */
  rules: MultiValuedQuestionRuleInputRulesItem[];
  /** Aggregation method */
  aggregation?: MultiValuedQuestionRuleInputAggregation;
}
