/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Aggregation method
 */
export type MultiValuedRuleInputAggregation = typeof MultiValuedRuleInputAggregation[keyof typeof MultiValuedRuleInputAggregation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MultiValuedRuleInputAggregation = {
  ALL: 'ALL',
  ANY: 'ANY',
  PARTIAL: 'PARTIAL',
} as const;
