/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Mode of choice matching: 'ALL' requires all correct choices to be selected, 'ANY' requires at least one, 'PARTIAL' gives credit for each correct choice selected minus each incorrect choice selected.
 */
export type MultipleChoiceQuestionRuleOutputMode = typeof MultipleChoiceQuestionRuleOutputMode[keyof typeof MultipleChoiceQuestionRuleOutputMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MultipleChoiceQuestionRuleOutputMode = {
  ALL: 'ALL',
  ANY: 'ANY',
  PARTIAL: 'PARTIAL',
} as const;
