/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { MultipleChoiceRuleOutputQuestionTypesItem } from './multipleChoiceRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { MultipleChoiceRuleOutputMode } from './multipleChoiceRuleOutputMode';

export interface MultipleChoiceRuleOutput {
  readonly question_types?: readonly MultipleChoiceRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'MULTIPLE_CHOICE';
  readonly display_name?: 'Multiple Choice';
  /**
   * Set of correct choices
   * @minItems 1
   */
  answer: string[];
  /** Mode of choice matching: 'ALL' requires all correct choices to be selected, 'ANY' requires at least one, 'PARTIAL' gives credit for each correct choice selected minus each incorrect choice selected. */
  mode?: MultipleChoiceRuleOutputMode;
  readonly description: string;
}
