/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { BonusRuleOutput } from './bonusRuleOutput';
import type { CompositeRuleOutput } from './compositeRuleOutput';
import type { CustomCodeRuleOutput } from './customCodeRuleOutput';
import type { CodeTestRuleOutput } from './codeTestRuleOutput';
import type { SimilarityRuleOutput } from './similarityRuleOutput';
import type { TextMatchRuleOutput } from './textMatchRuleOutput';
import type { KeywordsRuleOutput } from './keywordsRuleOutput';
import type { RegexRuleOutput } from './regexRuleOutput';
import type { LengthRuleOutput } from './lengthRuleOutput';
import type { MultiValuedRuleOutput } from './multiValuedRuleOutput';
import type { MultipleChoiceRuleOutput } from './multipleChoiceRuleOutput';
import type { NumberEqualRuleOutput } from './numberEqualRuleOutput';
import type { NumericRangeRuleOutput } from './numericRangeRuleOutput';

export type MultiValuedRuleOutputRulesItem = BonusRuleOutput | CompositeRuleOutput | CustomCodeRuleOutput | CodeTestRuleOutput | SimilarityRuleOutput | TextMatchRuleOutput | KeywordsRuleOutput | RegexRuleOutput | LengthRuleOutput | MultiValuedRuleOutput | MultipleChoiceRuleOutput | NumberEqualRuleOutput | NumericRangeRuleOutput;
