/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { MultipleChoiceQuestionRuleQuestionTypesItem } from './multipleChoiceQuestionRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { MultipleChoiceQuestionRuleMode } from './multipleChoiceQuestionRuleMode';

export interface MultipleChoiceQuestionRule {
  question_types?: MultipleChoiceQuestionRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  question_id: string;
  type?: 'MULTIPLE_CHOICE';
  /**
   * Set of correct choices
   * @minItems 1
   */
  answer: string[];
  /** Mode of choice matching: 'ALL' requires all correct choices to be selected, 'ANY' requires at least one, 'PARTIAL' gives credit for each correct choice selected minus each incorrect choice selected. */
  mode?: MultipleChoiceQuestionRuleMode;
}
