/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { MultiValuedRuleInputQuestionTypesItem } from './multiValuedRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { MultiValuedRuleInputRulesItem } from './multiValuedRuleInputRulesItem';
import type { MultiValuedRuleInputAggregation } from './multiValuedRuleInputAggregation';

export interface MultiValuedRuleInput {
  readonly question_types?: readonly MultiValuedRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'MULTI_VALUED';
  readonly name?: 'Multi Valued';
  /**
   * List of rules to apply to each value in the multi-valued answer
   * @minItems 1
   */
  rules: MultiValuedRuleInputRulesItem[];
  /** Aggregation method */
  aggregation?: MultiValuedRuleInputAggregation;
}
