/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { BonusRuleInput } from './bonusRuleInput';
import type { CompositeRuleInput } from './compositeRuleInput';
import type { ProgrammableRuleInput } from './programmableRuleInput';
import type { ProgrammingRuleInput } from './programmingRuleInput';
import type { TextMatchRuleInput } from './textMatchRuleInput';
import type { KeywordsRuleInput } from './keywordsRuleInput';
import type { RegexRuleInput } from './regexRuleInput';
import type { LengthRuleInput } from './lengthRuleInput';
import type { ManualRuleInput } from './manualRuleInput';
import type { MultiValuedRuleInput } from './multiValuedRuleInput';
import type { MultipleChoiceRuleInput } from './multipleChoiceRuleInput';
import type { NumberEqualRuleInput } from './numberEqualRuleInput';
import type { NumericRangeRuleInput } from './numericRangeRuleInput';

export type MultiValuedQuestionRuleInputRulesItem = BonusRuleInput | CompositeRuleInput | ProgrammableRuleInput | ProgrammingRuleInput | TextMatchRuleInput | KeywordsRuleInput | RegexRuleInput | LengthRuleInput | ManualRuleInput | MultiValuedRuleInput | MultipleChoiceRuleInput | NumberEqualRuleInput | NumericRangeRuleInput;
