/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { MultiValuedQuestionRuleOutputQuestionTypesItem } from './multiValuedQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { MultiValuedQuestionRuleOutputRulesItem } from './multiValuedQuestionRuleOutputRulesItem';
import type { MultiValuedQuestionRuleOutputAggregation } from './multiValuedQuestionRuleOutputAggregation';

export interface MultiValuedQuestionRuleOutput {
  readonly question_types?: readonly MultiValuedQuestionRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'MULTI_VALUED';
  readonly name?: 'Multi Valued';
  /**
   * List of rules to apply to each value in the multi-valued answer
   * @minItems 1
   */
  rules: MultiValuedQuestionRuleOutputRulesItem[];
  /** Aggregation method */
  aggregation?: MultiValuedQuestionRuleOutputAggregation;
  readonly description: string;
}
