/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { MultiValuedRuleOutputQuestionTypesItem } from './multiValuedRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { MultiValuedRuleOutputRulesItem } from './multiValuedRuleOutputRulesItem';
import type { MultiValuedRuleOutputAggregation } from './multiValuedRuleOutputAggregation';

export interface MultiValuedRuleOutput {
  readonly question_types?: readonly MultiValuedRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'MULTI_VALUED';
  readonly display_name?: 'Multi Valued';
  /**
   * List of rules to apply to each value in the multi-valued answer
   * @minItems 1
   */
  rules: MultiValuedRuleOutputRulesItem[];
  /** Aggregation method */
  aggregation?: MultiValuedRuleOutputAggregation;
  readonly description: string;
}
