/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { BonusRuleInput } from './bonusRuleInput';
import type { CompositeRuleInput } from './compositeRuleInput';
import type { CustomCodeRuleInput } from './customCodeRuleInput';
import type { CodeTestRuleInput } from './codeTestRuleInput';
import type { SimilarityRuleInput } from './similarityRuleInput';
import type { TextMatchRuleInput } from './textMatchRuleInput';
import type { KeywordsRuleInput } from './keywordsRuleInput';
import type { RegexRuleInput } from './regexRuleInput';
import type { LengthRuleInput } from './lengthRuleInput';
import type { MultiValuedRuleInput } from './multiValuedRuleInput';
import type { MultipleChoiceRuleInput } from './multipleChoiceRuleInput';
import type { NumberEqualRuleInput } from './numberEqualRuleInput';
import type { NumericRangeRuleInput } from './numericRangeRuleInput';

export type MultiValuedQuestionRuleInputRulesItem = BonusRuleInput | CompositeRuleInput | CustomCodeRuleInput | CodeTestRuleInput | SimilarityRuleInput | TextMatchRuleInput | KeywordsRuleInput | RegexRuleInput | LengthRuleInput | MultiValuedRuleInput | MultipleChoiceRuleInput | NumberEqualRuleInput | NumericRangeRuleInput;
