/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { MultiValuedRuleInputQuestionTypesItem } from './multiValuedRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { MultiValuedRuleInputRulesItem } from './multiValuedRuleInputRulesItem';
import type { MultiValuedRuleInputAggregation } from './multiValuedRuleInputAggregation';

export interface MultiValuedRuleInput {
  question_types?: MultiValuedRuleInputQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  type?: 'MULTI_VALUED';
  /**
   * List of rules to apply to each value in the multi-valued answer
   * @minItems 1
   */
  rules: MultiValuedRuleInputRulesItem[];
  /** Aggregation method */
  aggregation?: MultiValuedRuleInputAggregation;
}
