/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { MultipleChoiceQuestionRuleOutputQuestionTypesItem } from './multipleChoiceQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { MultipleChoiceQuestionRuleOutputMode } from './multipleChoiceQuestionRuleOutputMode';

export interface MultipleChoiceQuestionRuleOutput {
  readonly question_types?: readonly MultipleChoiceQuestionRuleOutputQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  question_id: string;
  readonly type?: 'MULTIPLE_CHOICE';
  readonly display_name?: 'Multiple Choice';
  /**
   * Set of correct choices
   * @minItems 1
   */
  answer: string[];
  /** Mode of choice matching: 'ALL' requires all correct choices to be selected, 'ANY' requires at least one, 'PARTIAL' gives credit for each correct choice selected minus each incorrect choice selected. */
  mode?: MultipleChoiceQuestionRuleOutputMode;
  readonly description: string;
}
