/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { NumberEqualRuleInputQuestionTypesItem } from './numberEqualRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { NumberEqualRuleInputAnswersItem } from './numberEqualRuleInputAnswersItem';
import type { NumberEqualConfig } from './numberEqualConfig';

export interface NumberEqualRuleInput {
  readonly question_types?: readonly NumberEqualRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'NUMBER_EQUAL';
  readonly name?: 'Number Equal';
  /**
   * List of acceptable numeric answers
   * @minItems 1
   */
  answers: NumberEqualRuleInputAnswersItem[];
  /** Configuration for numeric equality checks */
  config?: NumberEqualConfig;
}
