/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { NumberEqualRuleOutputQuestionTypesItem } from './numberEqualRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { NumberEqualRuleOutputAnswersItem } from './numberEqualRuleOutputAnswersItem';
import type { NumberEqualConfig } from './numberEqualConfig';

export interface NumberEqualRuleOutput {
  readonly question_types?: readonly NumberEqualRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'NUMBER_EQUAL';
  readonly display_name?: 'Number Equal';
  /**
   * List of acceptable numeric answers
   * @minItems 1
   */
  answers: NumberEqualRuleOutputAnswersItem[];
  /** Configuration for numeric equality checks */
  config?: NumberEqualConfig;
  readonly description: string;
}
