/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { NumberEqualQuestionRuleQuestionTypesItem } from './numberEqualQuestionRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { NumberEqualQuestionRuleAnswersItem } from './numberEqualQuestionRuleAnswersItem';
import type { NumberEqualConfig } from './numberEqualConfig';

export interface NumberEqualQuestionRule {
  question_types?: NumberEqualQuestionRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  question_id: string;
  type?: 'NUMBER_EQUAL';
  /**
   * List of acceptable numeric answers
   * @minItems 1
   */
  answers: NumberEqualQuestionRuleAnswersItem[];
  /** Configuration for numeric equality checks */
  config?: NumberEqualConfig;
}
