/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { NumberEqualQuestionRuleInputQuestionTypesItem } from './numberEqualQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { NumberEqualQuestionRuleInputAnswersItem } from './numberEqualQuestionRuleInputAnswersItem';
import type { NumberEqualConfig } from './numberEqualConfig';

export interface NumberEqualQuestionRuleInput {
  readonly question_types?: readonly NumberEqualQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'NUMBER_EQUAL';
  readonly display_name?: 'Number Equal';
  /**
   * List of acceptable numeric answers
   * @minItems 1
   */
  answers: NumberEqualQuestionRuleInputAnswersItem[];
  /** Configuration for numeric equality checks */
  config?: NumberEqualConfig;
}
