/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { NumberEqualQuestionRuleOutputQuestionTypesItem } from './numberEqualQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { NumberEqualQuestionRuleOutputAnswersItem } from './numberEqualQuestionRuleOutputAnswersItem';
import type { NumberEqualConfig } from './numberEqualConfig';

export interface NumberEqualQuestionRuleOutput {
  readonly question_types?: readonly NumberEqualQuestionRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'NUMBER_EQUAL';
  readonly name?: 'Number Equal';
  /**
   * List of acceptable numeric answers
   * @minItems 1
   */
  answers: NumberEqualQuestionRuleOutputAnswersItem[];
  /** Configuration for numeric equality checks */
  config?: NumberEqualConfig;
  readonly description: string;
}
