/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { NumberEqualRuleQuestionTypesItem } from './numberEqualRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { NumberEqualRuleAnswersItem } from './numberEqualRuleAnswersItem';
import type { NumberEqualConfig } from './numberEqualConfig';

export interface NumberEqualRule {
  question_types?: NumberEqualRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  type?: 'NUMBER_EQUAL';
  /**
   * List of acceptable numeric answers
   * @minItems 1
   */
  answers: NumberEqualRuleAnswersItem[];
  /** Configuration for numeric equality checks */
  config?: NumberEqualConfig;
}
