/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { NumericRangeQuestionRuleOutputQuestionTypesItem } from './numericRangeQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { NumericRangeQuestionRuleOutputMinValue } from './numericRangeQuestionRuleOutputMinValue';
import type { NumericRangeQuestionRuleOutputMaxValue } from './numericRangeQuestionRuleOutputMaxValue';

export interface NumericRangeQuestionRuleOutput {
  readonly question_types?: readonly NumericRangeQuestionRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'NUMERIC_RANGE';
  readonly name?: 'Numeric Range';
  /** Minimum acceptable value */
  min_value?: NumericRangeQuestionRuleOutputMinValue;
  /** Maximum acceptable value */
  max_value?: NumericRangeQuestionRuleOutputMaxValue;
  readonly description: string;
}
