/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { NumericRangeRuleInputQuestionTypesItem } from './numericRangeRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { NumericRangeRuleInputMinValue } from './numericRangeRuleInputMinValue';
import type { NumericRangeRuleInputMaxValue } from './numericRangeRuleInputMaxValue';

export interface NumericRangeRuleInput {
  readonly question_types?: readonly NumericRangeRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'NUMERIC_RANGE';
  readonly name?: 'Numeric Range';
  /** Minimum acceptable value */
  min_value?: NumericRangeRuleInputMinValue;
  /** Maximum acceptable value */
  max_value?: NumericRangeRuleInputMaxValue;
}
