/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { NumericRangeQuestionRuleInputQuestionTypesItem } from './numericRangeQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { NumericRangeQuestionRuleInputMinValue } from './numericRangeQuestionRuleInputMinValue';
import type { NumericRangeQuestionRuleInputMaxValue } from './numericRangeQuestionRuleInputMaxValue';

export interface NumericRangeQuestionRuleInput {
  readonly question_types?: readonly NumericRangeQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'NUMERIC_RANGE';
  readonly name?: 'Numeric Range';
  /** Minimum acceptable value */
  min_value?: NumericRangeQuestionRuleInputMinValue;
  /** Maximum acceptable value */
  max_value?: NumericRangeQuestionRuleInputMaxValue;
}
