/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { NumericRangeRuleOutputQuestionTypesItem } from './numericRangeRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { NumericRangeRuleOutputMinValue } from './numericRangeRuleOutputMinValue';
import type { NumericRangeRuleOutputMaxValue } from './numericRangeRuleOutputMaxValue';

export interface NumericRangeRuleOutput {
  readonly question_types?: readonly NumericRangeRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'NUMERIC_RANGE';
  readonly display_name?: 'Numeric Range';
  /** Minimum acceptable value */
  min_value?: NumericRangeRuleOutputMinValue;
  /** Maximum acceptable value */
  max_value?: NumericRangeRuleOutputMaxValue;
  readonly description: string;
}
