/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { NumericRangeQuestionRuleQuestionTypesItem } from './numericRangeQuestionRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { NumericRangeQuestionRuleMinValue } from './numericRangeQuestionRuleMinValue';
import type { NumericRangeQuestionRuleMaxValue } from './numericRangeQuestionRuleMaxValue';

export interface NumericRangeQuestionRule {
  question_types?: NumericRangeQuestionRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  question_id: string;
  type?: 'NUMERIC_RANGE';
  /** Minimum acceptable value */
  min_value?: NumericRangeQuestionRuleMinValue;
  /** Maximum acceptable value */
  max_value?: NumericRangeQuestionRuleMaxValue;
}
