/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { NumericRangeRuleQuestionTypesItem } from './numericRangeRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { NumericRangeRuleMinValue } from './numericRangeRuleMinValue';
import type { NumericRangeRuleMaxValue } from './numericRangeRuleMaxValue';

export interface NumericRangeRule {
  question_types?: NumericRangeRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  type?: 'NUMERIC_RANGE';
  /** Minimum acceptable value */
  min_value?: NumericRangeRuleMinValue;
  /** Maximum acceptable value */
  max_value?: NumericRangeRuleMaxValue;
}
