/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ParseSubmissionsRequestQuestionSet } from './parseSubmissionsRequestQuestionSet';
import type { ParseSubmissionsRequestRawSubmissions } from './parseSubmissionsRequestRawSubmissions';

export interface ParseSubmissionsRequest {
  use_stored_question_set?: boolean;
  use_stored_submissions?: boolean;
  question_set?: ParseSubmissionsRequestQuestionSet;
  raw_submissions?: ParseSubmissionsRequestRawSubmissions;
}
