/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ProgrammableQuestionRuleInputQuestionTypesItem } from './programmableQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { ProgrammableQuestionRuleInputParameters } from './programmableQuestionRuleInputParameters';
import type { ProgrammableQuestionRuleInputMode } from './programmableQuestionRuleInputMode';

export interface ProgrammableQuestionRuleInput {
  readonly question_types?: readonly ProgrammableQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'PROGRAMMABLE';
  readonly display_name?: 'Programmable';
  /** Code to evaluate the answer. Required variables: 'output', 'passed'. Optional variable: 'feedback'. */
  code?: string;
  /** Parameters that can be used in the code. */
  parameters?: ProgrammableQuestionRuleInputParameters;
  /** Mode of evaluation: 'PASS_FAIL' uses a boolean 'passed' variable, 'OUTPUT' uses the 'output' variable (0-1) for scoring. */
  mode?: ProgrammableQuestionRuleInputMode;
}
