/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Mode of evaluation: 'PASS_FAIL' uses a boolean 'passed' variable, 'OUTPUT' uses the 'output' variable (0-1) for scoring.
 */
export type ProgrammableQuestionRuleMode = typeof ProgrammableQuestionRuleMode[keyof typeof ProgrammableQuestionRuleMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProgrammableQuestionRuleMode = {
  PASS_FAIL: 'PASS_FAIL',
  OUTPUT: 'OUTPUT',
} as const;
