/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Mode of test case evaluation: 'ALL' requires all test cases to pass, 'ANY' requires at least one to pass, 'PARTIAL' gives credit for each test case passed.
 */
export type ProgrammingRuleInputMode = typeof ProgrammingRuleInputMode[keyof typeof ProgrammingRuleInputMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProgrammingRuleInputMode = {
  ALL: 'ALL',
  ANY: 'ANY',
  PARTIAL: 'PARTIAL',
} as const;
