/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

export type ProgrammableRuleInputQuestionTypesItem = typeof ProgrammableRuleInputQuestionTypesItem[keyof typeof ProgrammableRuleInputQuestionTypesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProgrammableRuleInputQuestionTypesItem = {
  TEXT: 'TEXT',
  CHOICE: 'CHOICE',
  NUMERIC: 'NUMERIC',
  MULTI_VALUED: 'MULTI_VALUED',
} as const;
