/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ProgrammableQuestionRuleQuestionTypesItem } from './programmableQuestionRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { ProgrammableQuestionRuleMode } from './programmableQuestionRuleMode';

export interface ProgrammableQuestionRule {
  question_types?: ProgrammableQuestionRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  question_id: string;
  type?: 'PROGRAMMABLE';
  /** Code to evaluate the answer. Required variables: 'output', 'passed'. Optional variable: 'feedback'. */
  code?: string;
  /** Mode of evaluation: 'PASS_FAIL' uses a boolean 'passed' variable, 'OUTPUT' uses the 'output' variable (0-1) for scoring. */
  mode?: ProgrammableQuestionRuleMode;
}
