/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ProgrammingQuestionRuleOutputQuestionTypesItem } from './programmingQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { ProgrammingTestCase } from './programmingTestCase';
import type { ProgrammingConfig } from './programmingConfig';
import type { ProgrammingQuestionRuleOutputMode } from './programmingQuestionRuleOutputMode';

export interface ProgrammingQuestionRuleOutput {
  readonly question_types?: readonly ProgrammingQuestionRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'PROGRAMMING';
  readonly display_name?: 'Programming';
  /**
   * List of test cases to run against the code
   * @minItems 1
   */
  testcases: ProgrammingTestCase[];
  /** Programming language of the code to be tested */
  language?: 'python';
  /** Configuration for code testing */
  config?: ProgrammingConfig;
  /** Whether to show the evaluated expected output in feedback */
  show_evaluated_expected?: boolean;
  /** Mode of test case evaluation: 'ALL' requires all test cases to pass, 'ANY' requires at least one to pass, 'PARTIAL' gives credit for each test case passed. */
  mode?: ProgrammingQuestionRuleOutputMode;
  readonly description: string;
}
