/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ProgrammableQuestionRuleOutputQuestionTypesItem } from './programmableQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { ProgrammableQuestionRuleOutputParameters } from './programmableQuestionRuleOutputParameters';
import type { ProgrammableQuestionRuleOutputMode } from './programmableQuestionRuleOutputMode';

export interface ProgrammableQuestionRuleOutput {
  readonly question_types?: readonly ProgrammableQuestionRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'PROGRAMMABLE';
  readonly name?: 'Programmable';
  /** Code to evaluate the answer. Required variables: 'output', 'passed'. Optional variable: 'feedback'. */
  code?: string;
  /** Parameters that can be used in the code. */
  parameters?: ProgrammableQuestionRuleOutputParameters;
  /** Mode of evaluation: 'PASS_FAIL' uses a boolean 'passed' variable, 'OUTPUT' uses the 'output' variable (0-1) for scoring. */
  mode?: ProgrammableQuestionRuleOutputMode;
  readonly description: string;
}
