/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { IntParameter } from './intParameter';
import type { FloatParameter } from './floatParameter';
import type { StringParameter } from './stringParameter';
import type { BooleanParameter } from './booleanParameter';
import type { ListParameterOutput } from './listParameterOutput';
import type { DictParameterOutput } from './dictParameterOutput';

/**
 * Parameters that can be used in the code.
 */
export type ProgrammableQuestionRuleOutputParameters = {[key: string]: IntParameter | FloatParameter | StringParameter | BooleanParameter | ListParameterOutput | DictParameterOutput};
