/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

export interface ProgrammingConfig {
  /** Code to prepend to the student's answer */
  prepend_code?: string;
  /** Code to append to the student's answer */
  append_code?: string;
  /** Number of spaces to indent the student's code when embedding it */
  indent?: number;
  /** Time limit in seconds for code execution */
  time_limit?: number;
}
