/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

export interface ProgrammingTestCase {
  /** Input for the test case */
  expression: string;
  /** Expected output for the test case */
  expected: string;
}
