/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ProgrammableRuleInputQuestionTypesItem } from './programmableRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { ProgrammableRuleInputMode } from './programmableRuleInputMode';

export interface ProgrammableRuleInput {
  readonly question_types?: readonly ProgrammableRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'PROGRAMMABLE';
  readonly name?: 'Programmable';
  /** Code to evaluate the answer. Required variables: 'output', 'passed'. Optional variable: 'feedback'. */
  code?: string;
  /** Mode of evaluation: 'PASS_FAIL' uses a boolean 'passed' variable, 'OUTPUT' uses the 'output' variable (0-1) for scoring. */
  mode?: ProgrammableRuleInputMode;
}
