/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ProgrammableRuleOutputQuestionTypesItem } from './programmableRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { ProgrammableRuleOutputParameters } from './programmableRuleOutputParameters';
import type { ProgrammableRuleOutputMode } from './programmableRuleOutputMode';

export interface ProgrammableRuleOutput {
  readonly question_types?: readonly ProgrammableRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'PROGRAMMABLE';
  readonly name?: 'Programmable';
  /** Code to evaluate the answer. Required variables: 'output', 'passed'. Optional variable: 'feedback'. */
  code?: string;
  /** Parameters that can be used in the code. */
  parameters?: ProgrammableRuleOutputParameters;
  /** Mode of evaluation: 'PASS_FAIL' uses a boolean 'passed' variable, 'OUTPUT' uses the 'output' variable (0-1) for scoring. */
  mode?: ProgrammableRuleOutputMode;
  readonly description: string;
}
