/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ChoiceOptionDrift } from './choiceOptionDrift';

export interface QuestionSetDrift {
  missing_question_ids?: string[];
  extra_question_ids?: string[];
  choice_option_drifts?: ChoiceOptionDrift[];
  has_drift?: boolean;
}
