/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { QuestionResultOutput } from './questionResultOutput';

export interface QuestionResult {
  /** Output generated from evaluating the answer */
  output: QuestionResultOutput;
  /** Whether the answer passed the rule check */
  passed: boolean;
  /** Feedback or comments */
  feedback: string;
  /** ID of the rule that was applied */
  rule: string;
  /** Whether the result has been graded */
  graded?: boolean;
  /** Points awarded for this question */
  points: number;
  /** Maximum points possible */
  max_points: number;
}
