/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ChoiceQuestion } from './choiceQuestion';
import type { MultiValuedQuestion } from './multiValuedQuestion';
import type { TextQuestion } from './textQuestion';
import type { NumericQuestion } from './numericQuestion';

export type QuestionSetInputQuestionMap = {[key: string]: ChoiceQuestion | MultiValuedQuestion | TextQuestion | NumericQuestion};
