/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { QuestionSetOutput } from './questionSetOutput';
import type { SectionStatus } from './sectionStatus';

export interface QuestionSetResponse {
  question_set: QuestionSetOutput;
  status: SectionStatus;
}
