/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { RawSubmissionResultMap } from './rawSubmissionResultMap';
import type { RawSubmissionRawAnswerMap } from './rawSubmissionRawAnswerMap';

export interface RawSubmission {
  student_id: string;
  result_map?: RawSubmissionResultMap;
  raw_answer_map: RawSubmissionRawAnswerMap;
}
