/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { QuestionResult } from './questionResult';

export type RawSubmissionResultMap = {[key: string]: QuestionResult};
