/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { RegexRuleQuestionTypesItem } from './regexRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { RegexConfig } from './regexConfig';

export interface RegexRule {
  question_types?: RegexRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  type?: 'REGEX';
  /** Regular expression pattern to match against the answer */
  pattern: string;
  /** Configuration for regex matching behavior */
  config?: RegexConfig;
}
