/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

export interface RegexConfig {
  /** Ignore case when matching */
  ignore_case?: boolean;
  /** Multi-line matching */
  multi_line?: boolean;
  /** Dot matches all characters including newlines */
  dotall?: boolean;
}
