/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { RegexQuestionRuleQuestionTypesItem } from './regexQuestionRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { RegexConfig } from './regexConfig';

export interface RegexQuestionRule {
  question_types?: RegexQuestionRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  question_id: string;
  type?: 'REGEX';
  /** Regular expression pattern to match against the answer */
  pattern: string;
  /** Configuration for regex matching behavior */
  config?: RegexConfig;
}
