/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { RegexQuestionRuleInputQuestionTypesItem } from './regexQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { RegexConfig } from './regexConfig';

export interface RegexQuestionRuleInput {
  readonly question_types?: readonly RegexQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'REGEX';
  readonly display_name?: 'Regex';
  /** Regular expression pattern to match against the answer */
  pattern: string;
  /** Configuration for regex matching behavior */
  config?: RegexConfig;
}
