/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { RubricOverviewResponseQuestionRulesItem } from './rubricOverviewResponseQuestionRulesItem';
import type { RubricOverviewResponseGlobalRulesItem } from './rubricOverviewResponseGlobalRulesItem';
import type { RubricCoverage } from './rubricCoverage';
import type { StaleRuleReference } from './staleRuleReference';
import type { SectionStatus } from './sectionStatus';

export interface RubricOverviewResponse {
  question_rules: RubricOverviewResponseQuestionRulesItem[];
  global_rules: RubricOverviewResponseGlobalRulesItem[];
  coverage: RubricCoverage;
  stale_rules: StaleRuleReference[];
  status: SectionStatus;
}
