/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { RubricOutput } from './rubricOutput';
import type { SectionStatus } from './sectionStatus';

export interface RubricResponse {
  rubric: RubricOutput;
  status: SectionStatus;
}
