/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssumptionSetQuestionRuleInput } from './assumptionSetQuestionRuleInput';
import type { BonusQuestionRule } from './bonusQuestionRule';
import type { CompositeQuestionRuleInput } from './compositeQuestionRuleInput';
import type { ProgrammableQuestionRule } from './programmableQuestionRule';
import type { ProgrammingQuestionRule } from './programmingQuestionRule';
import type { TextMatchQuestionRule } from './textMatchQuestionRule';
import type { KeywordsQuestionRule } from './keywordsQuestionRule';
import type { RegexQuestionRule } from './regexQuestionRule';
import type { LengthQuestionRule } from './lengthQuestionRule';
import type { ManualQuestionRule } from './manualQuestionRule';
import type { MultiValuedQuestionRuleInput } from './multiValuedQuestionRuleInput';
import type { MultipleChoiceQuestionRule } from './multipleChoiceQuestionRule';
import type { NumberEqualQuestionRule } from './numberEqualQuestionRule';
import type { NumericRangeQuestionRule } from './numericRangeQuestionRule';
import type { AssumptionSetMultiQuestionRuleInput } from './assumptionSetMultiQuestionRuleInput';
import type { ConditionalMultiQuestionRuleInput } from './conditionalMultiQuestionRuleInput';

export type RubricInputRulesItem = AssumptionSetQuestionRuleInput | BonusQuestionRule | CompositeQuestionRuleInput | ProgrammableQuestionRule | ProgrammingQuestionRule | TextMatchQuestionRule | KeywordsQuestionRule | RegexQuestionRule | LengthQuestionRule | ManualQuestionRule | MultiValuedQuestionRuleInput | MultipleChoiceQuestionRule | NumberEqualQuestionRule | NumericRangeQuestionRule | AssumptionSetMultiQuestionRuleInput | ConditionalMultiQuestionRuleInput;
