/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { AssumptionSetQuestionRuleInput } from './assumptionSetQuestionRuleInput';
import type { BonusQuestionRuleInput } from './bonusQuestionRuleInput';
import type { CompositeQuestionRuleInput } from './compositeQuestionRuleInput';
import type { CustomCodeQuestionRuleInput } from './customCodeQuestionRuleInput';
import type { CodeTestQuestionRuleInput } from './codeTestQuestionRuleInput';
import type { SimilarityQuestionRuleInput } from './similarityQuestionRuleInput';
import type { TextMatchQuestionRuleInput } from './textMatchQuestionRuleInput';
import type { KeywordsQuestionRuleInput } from './keywordsQuestionRuleInput';
import type { RegexQuestionRuleInput } from './regexQuestionRuleInput';
import type { LengthQuestionRuleInput } from './lengthQuestionRuleInput';
import type { MultiValuedQuestionRuleInput } from './multiValuedQuestionRuleInput';
import type { MultipleChoiceQuestionRuleInput } from './multipleChoiceQuestionRuleInput';
import type { NumberEqualQuestionRuleInput } from './numberEqualQuestionRuleInput';
import type { NumericRangeQuestionRuleInput } from './numericRangeQuestionRuleInput';
import type { AssumptionSetMultiQuestionRuleInput } from './assumptionSetMultiQuestionRuleInput';
import type { ConditionalMultiQuestionRuleInput } from './conditionalMultiQuestionRuleInput';
import type { CustomCodeMultiQuestionRuleInput } from './customCodeMultiQuestionRuleInput';

export type RubricInputRulesItem = AssumptionSetQuestionRuleInput | BonusQuestionRuleInput | CompositeQuestionRuleInput | CustomCodeQuestionRuleInput | CodeTestQuestionRuleInput | SimilarityQuestionRuleInput | TextMatchQuestionRuleInput | KeywordsQuestionRuleInput | RegexQuestionRuleInput | LengthQuestionRuleInput | MultiValuedQuestionRuleInput | MultipleChoiceQuestionRuleInput | NumberEqualQuestionRuleInput | NumericRangeQuestionRuleInput | AssumptionSetMultiQuestionRuleInput | ConditionalMultiQuestionRuleInput | CustomCodeMultiQuestionRuleInput;
