/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { SignupRequestName } from './signupRequestName';

export interface SignupRequest {
  email: string;
  /** @maxLength 255 */
  name?: SignupRequestName;
  /**
   * @minLength 12
   * @maxLength 128
   */
  password: string;
}
