/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { SimilarityRuleInputQuestionTypesItem } from './similarityRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { SimilarityRuleInputAlgorithm } from './similarityRuleInputAlgorithm';

/**
 * A rule that checks for similarity between the student's answer and a reference text.
 */
export interface SimilarityRuleInput {
  readonly question_types?: readonly SimilarityRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'SIMILARITY';
  readonly display_name?: 'Similarity';
  /** Reference answers for similarity comparison */
  references: string[];
  /** Similarity threshold for passing the rule (0 to 1) */
  threshold?: number;
  /** Similarity algorithm to use (options: 'levenshtein', 'jaro_winkler', 'transformer'). 'transformer' uses the BAAI/bge-small-en-v1.5 model and requires the 'ml' extra. */
  algorithm?: SimilarityRuleInputAlgorithm;
}
