/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { SimilarityQuestionRuleInputQuestionTypesItem } from './similarityQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { SimilarityQuestionRuleInputAlgorithm } from './similarityQuestionRuleInputAlgorithm';

export interface SimilarityQuestionRuleInput {
  readonly question_types?: readonly SimilarityQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'SIMILARITY';
  readonly name?: 'Similarity';
  /** Reference answers for similarity comparison */
  references: string[];
  /** Similarity threshold for passing the rule (0 to 1) */
  threshold?: number;
  /** Similarity algorithm to use (options: 'levenshtein', 'jaro_winkler', 'transformer'). 'transformer' uses the BAAI/bge-small-en-v1.5 model and requires the 'ml' extra. */
  algorithm?: SimilarityQuestionRuleInputAlgorithm;
}
