/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Similarity algorithm to use (options: 'levenshtein', 'jaro_winkler', 'transformer'). 'transformer' uses the BAAI/bge-small-en-v1.5 model and requires the 'ml' extra.
 */
export type SimilarityQuestionRuleInputAlgorithm = typeof SimilarityQuestionRuleInputAlgorithm[keyof typeof SimilarityQuestionRuleInputAlgorithm];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SimilarityQuestionRuleInputAlgorithm = {
  levenshtein: 'levenshtein',
  jaro_winkler: 'jaro_winkler',
  transformer: 'transformer',
} as const;
