/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { SimilarityQuestionRuleOutputQuestionTypesItem } from './similarityQuestionRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';
import type { SimilarityQuestionRuleOutputAlgorithm } from './similarityQuestionRuleOutputAlgorithm';

export interface SimilarityQuestionRuleOutput {
  readonly id: string;
  readonly question_types: readonly SimilarityQuestionRuleOutputQuestionTypesItem[];
  readonly constraints: readonly QuestionConstraint[];
  readonly scope: 'question';
  question_id: string;
  readonly type: 'SIMILARITY';
  readonly display_name: 'Similarity';
  /**
   * Reference answers for similarity comparison
   * @minItems 1
   */
  references: string[];
  /** Similarity threshold for passing the rule (0 to 1) */
  threshold: number;
  /** Similarity algorithm to use (options: 'levenshtein', 'jaro_winkler', 'transformer'). 'transformer' uses the BAAI/bge-small-en-v1.5 model and requires the 'ml' extra. */
  algorithm: SimilarityQuestionRuleOutputAlgorithm;
  readonly description: string;
}
