/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { SourceDataResponseStudentIdColumn } from './sourceDataResponseStudentIdColumn';

export interface SourceDataResponse {
  headers: string[];
  rows: string[][];
  total_rows: number;
  student_id_column?: SourceDataResponseStudentIdColumn;
}
