/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { SubmissionResultMap } from './submissionResultMap';
import type { SubmissionAnswerMap } from './submissionAnswerMap';

export interface Submission {
  student_id: string;
  result_map?: SubmissionResultMap;
  answer_map: SubmissionAnswerMap;
}
