/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { SubmissionsImportConfigAnswerColumns } from './submissionsImportConfigAnswerColumns';
import type { SubmissionsImportConfigPointColumns } from './submissionsImportConfigPointColumns';

export interface SubmissionsImportConfig {
  answer_columns?: SubmissionsImportConfigAnswerColumns;
  point_columns?: SubmissionsImportConfigPointColumns;
}
