/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { TextMatchRuleOutputQuestionTypesItem } from './textMatchRuleOutputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';

export interface TextMatchRuleOutput {
  readonly question_types?: readonly TextMatchRuleOutputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  readonly type?: 'TEXT_MATCH';
  readonly name?: 'Text Match';
  /**
   * List of acceptable exact answers
   * @minItems 1
   */
  answers: string[];
  readonly description: string;
}
