/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { TextMatchRuleQuestionTypesItem } from './textMatchRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';

export interface TextMatchRule {
  question_types?: TextMatchRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  type?: 'TEXT_MATCH';
  /**
   * List of acceptable exact answers
   * @minItems 1
   */
  answers: string[];
}
