/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { TextMatchQuestionRuleQuestionTypesItem } from './textMatchQuestionRuleQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';

export interface TextMatchQuestionRule {
  question_types?: TextMatchQuestionRuleQuestionTypesItem[];
  constraints?: QuestionConstraint[];
  question_id: string;
  type?: 'TEXT_MATCH';
  /**
   * List of acceptable exact answers
   * @minItems 1
   */
  answers: string[];
}
