/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { TextMatchQuestionRuleInputQuestionTypesItem } from './textMatchQuestionRuleInputQuestionTypesItem';
import type { QuestionConstraint } from './questionConstraint';

export interface TextMatchQuestionRuleInput {
  readonly question_types?: readonly TextMatchQuestionRuleInputQuestionTypesItem[];
  readonly constraints?: readonly QuestionConstraint[];
  question_id: string;
  readonly type?: 'TEXT_MATCH';
  readonly name?: 'Text Match';
  /**
   * List of acceptable exact answers
   * @minItems 1
   */
  answers: string[];
}
