/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateMeRequestName } from './updateMeRequestName';
import type { UpdateMeRequestEmail } from './updateMeRequestEmail';
import type { UpdateMeRequestCurrentPassword } from './updateMeRequestCurrentPassword';
import type { UpdateMeRequestNewPassword } from './updateMeRequestNewPassword';

export interface UpdateMeRequest {
  /** @maxLength 255 */
  name?: UpdateMeRequestName;
  email?: UpdateMeRequestEmail;
  current_password?: UpdateMeRequestCurrentPassword;
  /**
   * @minLength 12
   * @maxLength 128
   */
  new_password?: UpdateMeRequestNewPassword;
}
