/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

export interface UploadSourceDataRequest {
  /** Processed CSV text */
  data: string;
  /** Name of the student ID column */
  student_id_column: string;
}
