/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */

export interface UploadSourceDataRequest {
  /** Processed CSV text (rows trimmed, student IDs optionally encrypted) */
  data: string;
  /** Name of the student ID column in the uploaded CSV */
  student_id_column: string;
}
