/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * GradeFlow API
 * Thin FastAPI wrapper over GradeFlow Engine
 * OpenAPI spec version: 0.1.0
 */
import type { ValidateRubricRequestRubric } from './validateRubricRequestRubric';
import type { ValidateRubricRequestQuestionSet } from './validateRubricRequestQuestionSet';

export interface ValidateRubricRequest {
  use_stored_rubric?: boolean;
  use_stored_question_set?: boolean;
  rubric?: ValidateRubricRequestRubric;
  question_set?: ValidateRubricRequestQuestionSet;
}
